syntax = "proto3";

package supplier;

option go_package = "github.com/pepshot/SoftPlace/gen/supplier;supplierpb";

service SupplierService {
  rpc GetModule(GetModuleRequest) returns (ModuleResponse);
  rpc ReserveModules(ReserveModulesRequest) returns (ReserveModulesResponse);
  rpc ReleaseModules(ReleaseModulesRequest) returns (ReleaseModulesResponse);
}

message GetModuleRequest {
  string module_id = 1;
}

message ModuleResponse {
  string id = 1;
  string name = 2;
  string code = 3;
  double price = 4;
  int32 stock_count = 5;
}

message ModuleItem {
  string module_id = 1;
  int32 count = 2;
}

message ReserveModulesRequest {
  repeated ModuleItem items = 1;
}

message ReserveModulesResponse {
  bool success = 1;
  string message = 2;
}

message ReleaseModulesRequest {
  repeated ModuleItem items = 1;
}

message ReleaseModulesResponse {
  bool success = 1;
  string message = 2;
}