// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import (
	"fmt"
	"strings"

	"github.com/swaggo/swag"
)

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {}
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "Supplier Service API",
	Description: "Supplier service API",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.ReplaceAll(sInfo.Description, "\n", "\\n")
	return fmt.Sprintf(docTemplate,
		strings.Join(sInfo.Schemes, ","),
		sInfo.Title,
		sInfo.Description,
		sInfo.Version,
		sInfo.Host,
		sInfo.BasePath,
	)
}

func init() {
	swag.Register(swag.Name, &s{})
}
